### ISSUE TITLE
dupe bug

### ISSUE THREAD

**Issue by Gamewalker** [gigabit101/StevesFactoryManager#36]
Hey,
I have a setup with MIM pulling from one chest into item valve and sending redstone pulse to atomic reconstructor from actually additions and grabbing the result and putting it into another chest to import it in my storage. The moment the valve picks the stuff up again, it dupes the items and fills the whole chest with the result.

**Comment by Ezelberoth** [comment]
I am also having this issue. When combined with ProjectE and the Energy Condensers, you get MASSIVE amounts of EMC like stupid fast. I was having it take milled items from my SAG Mill, and put it into the condenser, but when it took one item, it literally filled every available slot with that item, instead of only putting it in one slot, so instead of one item being moved, one item is picked up, and my chest now has one item in every slot. when the next item comes in, now all slots have 2-3 items. I can't even empty the chest fast enough.

**Comment by gigabit101** [comment]
fixed in 1.12.1
