### ISSUE TITLE
Block Gate Dup Bug

### ISSUE THREAD

**Issue by MindCaged** [gigabit101/StevesFactoryManager#37]
Using version 1.10.2-1.0.12.

Okay, I was trying to make an auto gravel to flint machine, I put a block gate with the side button facing back, a factory manager next to it, and a chest on top of the manager. I set it to import stuff from the gate, into the chest, then import from the chest, and place 1 gravel in front of the block gate. The idea being it would keep placing and breaking the gravel until it was converted to flint. There's better ways of doing it in my instance, but I wanted to try this way. Only thing was I put one gravel in, it placed it, then I opened the chest and every slot was filled with 1 flint, and it didn't break the gravel.

**Comment by RobertLSnead** [comment]
When using the block gate to place block into a chest(example iron chest) it tries to place it into all the available slots at once instead of it checking for an available slot and then splitting the stack between the next available slots.  It does not appear to be checking the slots prior or maybe a bad method.  Tested with one block of Living Wood (Botanaia).  I should mention that the method being used is a for loop with condition testing.

Snap Shots are Attached!

![test_snapshot_1](https://cloud.githubusercontent.com/assets/5366796/21829384/9d595f0e-d763-11e6-9ebb-0a15e1cb44ff.png)
![test_snapshot_2](https://cloud.githubusercontent.com/assets/5366796/21829387/a1db93d0-d763-11e6-818e-e292dc12cabb.png)
![test_snapshot_3](https://cloud.githubusercontent.com/assets/5366796/21829393/a54780f6-d763-11e6-9943-c0700af2a7ed.png)


    Minecraft: 1.10.2
    Forge: 12.18.2.2185
    Steves Factory Manager: 1.0.12

**Comment by Protheus** [comment]
https://www.youtube.com/watch?v=XGscDHRm3YM is the tutorial used to automate living rock.

- I combined advanced cable cluster with a block gate. Placed them and shift-Richt click them.
- I setup the code as per video
- it places a stone on each cable cluster (advanced cable cluster with a block gate) when the trigger is enabled
- when living rock is created, it fills the whole chest (32 per slot) with living rock instead of just 8 in the first slot.

Here is the empty chest and in the background the livingrock:
![2017-01-14_00 49 57](https://cloud.githubusercontent.com/assets/1455178/21949592/ee550362-d9f3-11e6-878f-3bf5fd524896.png)

When the gates activate it fills the whole chest:
![2017-01-14_00 50 22](https://cloud.githubusercontent.com/assets/1455178/21949608/04d8cb78-d9f4-11e6-9be7-1411cf73716b.png)

MC: 1.10.2
Forge: 2202
StevesFactoryManager-1.10.2-1.0.12

**Comment by RobertLSnead** [comment]
After further tests it seems to be doing this will all blocks.  There has to be an issue with either the input or output functions.  Haven't tested if it is only tied to the block gates.  Going to try chest to chest :p  Also stone placement on the servers is not working and trys to place the whole stack with the block gate.

EDIT:
Tried the input and output with chest to chest and there was no issues.  The issues seems to lie completely with the Block Gate!!!!

**Comment by gigabit101** [comment]
fixed in 1.12.1
